version: "3.1"

services:
  jobmanager:
      image: flink:1.13.2
      hostname: "jobmanager"
      expose:
        - "6123"
      ports:
        - "8082:8081"
      command: jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=jobmanager
      depends_on:
        - kafka
        - mysql
  taskmanager:
      image: flink:1.13.2
      expose:
        - "6121"
        - "6122"
      depends_on:
        - jobmanager
      command: taskmanager
      links:
        - jobmanager:jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=jobmanager
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    ports:
      - '2181:2181'
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    networks:
      - canal

  kafka:
    image: bitnami/kafka:2.2.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092, EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: unless-stopped

    networks:
      - canal

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
    - ./conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
    - ./conf/init.d:/docker-entrypoint-initdb.d/init.d
    networks:
      - canal

  canal-server:
    image: canal/canal-server:v1.1.5
    depends_on:
      - mysql
      - kafka
    ports:
      - 11111:11111
    volumes:
      - ./conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./conf/instance.properties:/home/admin/canal-server/conf/data_pipe/instance.properties
    restart: unless-stopped
    networks:
      - canal
  kafka-manager:
      image: sheepkiller/kafka-manager
      environment:
        ZK_HOSTS: zookeeper:2181
      ports:
        - "9001:9000"
      expose:
        - "9001"
      networks:
        - canal
  elasticsearch:
      image: elastic/elasticsearch:7.6.0
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
      ports:
        - "9200:9200"
        - "9300:9300"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
  kibana:
    image: elastic/kibana:7.6.0
    ports:
      - "5601:5601"

networks:
  canal:
    driver: bridge

volumes:
  zookeeper:
  kafka:
  canal:
  mysql: